export const shoppingCategories = [
  "Electronics",
  "Clothing",
  "Home and Furniture",
  "Books and Media",
  "Beauty and Personal Care",
  "Sports and Outdoors",
  "Toys and Games",
  "Automotive",
  "Appliances",
  "Jewelry",
  "Health and Wellness",
  "Pet Supplies",
  "Grocery",
  "Office Supplies",
  "Movies and Music",
  "Outdoor and Garden",
  "Baby and Kids",
  "Crafts and Hobbies",
  "Shoes",
  "Gifts and Collectibles",
];
